services:
  api:
    image: rodrigoleitzke/cadastro-veiculos:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - API_KEY=minha-chave-secreta-ficticia-veiculos
    volumes:
      - db_data:/app
    restart: unless-stopped

volumes:
  db_data: